CREATE TABLE IF NOT EXISTS `site_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `firm_id` bigint unsigned NOT NULL,
  `site_id` bigint unsigned NOT NULL,
  `calendar_key` varchar(50) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NULL,
  `location` varchar(255) DEFAULT NULL,
  `start_at` datetime NOT NULL,
  `end_at` datetime NOT NULL,
  `is_all_day` tinyint(1) NOT NULL DEFAULT 0,
  `color` varchar(9) NOT NULL DEFAULT '#ffffff',
  `bg_color` varchar(9) NOT NULL DEFAULT '#1abc9c',
  `border_color` varchar(9) NOT NULL DEFAULT '#1abc9c',
  `created_by` bigint unsigned NOT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_site_events_site` (`site_id`),
  KEY `idx_site_events_firm` (`firm_id`),
  KEY `idx_site_events_range` (`start_at`,`end_at`),
  KEY `idx_site_events_calendar` (`calendar_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
